[versions]
com-google-dagger = "2.57.2"
# @keep this version
compileSDK = "36"
# @keep this version
targetSDK = "36"
# @keep this version
minSDK = "21"
org-apache-groovy = "4.0.29"
org-jetbrains-kotlin = "2.2.0"
androidx-annotation = "1.9.1"
androidx-appcompat = "1.7.1"
androidx-recyclerview = "1.4.0"
com-android-tools-build-gradle = "8.13.0"
com-github-ben-manes-gradle-versions-plugin = "0.52.0"
com-github-johnrengelman-shadow = "8.1.1"
com-google-android-material = "1.13.0"
com-jakewharton-rx3-replaying-share = "3.0.0"
com-jakewharton-rxbinding4-rxbinding = "4.0.0"
com-jakewharton-rxrelay3-rxrelay = "3.0.1"
gradle-plugin-org-codehaus-groovy-groovy-android-gradle-plugin = "3.0.0"
io-github-gradle-nexus-publish-plugin = "2.0.0"
io-reactivex-rxjava3-rxandroid = "3.0.2"
io-reactivex-rxjava3-rxjava = "3.1.12"
io-reactivex-rxjava3-rxkotlin = "3.0.1"
net-bytebuddy-byte-buddy = "1.17.8"
org-junit-jupiter-junit-jupiter = "6.0.1"
org-junit-platform-junit-platform-launcher = "6.0.1"
org-objenesis = "3.4"
org-spockframework-spock-core = "2.4-M6-groovy-4.0"
nl-littlerobots-version-catalog-update = "1.0.1"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
com-android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "com-android-tools-build-gradle" }
com-github-ben-manes-gradle-versions-plugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "com-github-ben-manes-gradle-versions-plugin" }
com-github-johnrengelman-shadow = { module = "com.github.johnrengelman:shadow", version.ref = "com-github-johnrengelman-shadow" }
com-google-android-material = { module = "com.google.android.material:material", version.ref = "com-google-android-material" }
com-google-dagger = { module = "com.google.dagger:dagger", version.ref = "com-google-dagger" }
com-google-dagger-dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "com-google-dagger" }
com-jakewharton-rx3-replaying-share = { module = "com.jakewharton.rx3:replaying-share", version.ref = "com-jakewharton-rx3-replaying-share" }
com-jakewharton-rxbinding4-rxbinding = { module = "com.jakewharton.rxbinding4:rxbinding", version.ref = "com-jakewharton-rxbinding4-rxbinding" }
com-jakewharton-rxrelay3-rxrelay = { module = "com.jakewharton.rxrelay3:rxrelay", version.ref = "com-jakewharton-rxrelay3-rxrelay" }
gradle-plugin-org-codehaus-groovy-groovy-android-gradle-plugin = { module = "gradle.plugin.org.codehaus.groovy:groovy-android-gradle-plugin", version.ref = "gradle-plugin-org-codehaus-groovy-groovy-android-gradle-plugin" }
io-github-gradle-nexus-publish-plugin = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "io-github-gradle-nexus-publish-plugin" }
io-reactivex-rxjava3-rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "io-reactivex-rxjava3-rxandroid" }
io-reactivex-rxjava3-rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "io-reactivex-rxjava3-rxjava" }
io-reactivex-rxjava3-rxkotlin = { module = "io.reactivex.rxjava3:rxkotlin", version.ref = "io-reactivex-rxjava3-rxkotlin" }
net-bytebuddy-byte-buddy = { module = "net.bytebuddy:byte-buddy", version.ref = "net-bytebuddy-byte-buddy" }
org-apache-groovy = { module = "org.apache.groovy:groovy", version.ref = "org-apache-groovy" }
org-jetbrains-kotlin-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "org-jetbrains-kotlin" }
org-junit-jupiter-junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "org-junit-jupiter-junit-jupiter" }
org-junit-platform-junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "org-junit-platform-junit-platform-launcher" }
org-objenesis = { module = "org.objenesis:objenesis", version.ref = "org-objenesis" }
org-spockframework-spock-core = { module = "org.spockframework:spock-core", version.ref = "org-spockframework-spock-core" }

[plugins]
nl-littlerobots-version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "nl-littlerobots-version-catalog-update" }
